rails-girl-demo-master/rails-girl-demo-master/config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  resources :products, only: [:index, :show]

end

rails-girl-demo-master/rails-girl-demo-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-girl-demo-master/rails-girl-demo-master/app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true, length: {in: 5..255}
    validates :brand, presence: true, length: {in: 5..100}
    validates :price, inclusion: 1..1000000000
    validates  :image, presence: true
  end

rails-girl-demo-master/rails-girl-demo-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-girl-demo-master/rails-girl-demo-master/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def show
  @product = Product.find(params[:id])
  end
end

rails-girl-demo-master/rails-girl-demo-master/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-girl-demo-master/rails-girl-demo-master/app/helpers/products_helper.rb
module ProductsHelper
end

rails-girl-demo-master/rails-girl-demo-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Rails Girl Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light navbar-expand-md">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">
          Rails Girl Shop
        </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>">Products</a>
          </li>
        </ul>
      </div>
    </nav>
    <main class="pt-3 container">
      <%= yield %>
    </main>
  </body>
</html>

rails-girl-demo-master/rails-girl-demo-master/app/views/products/_product.html.erb
<div class="product col-md-4 mb-3">
  <a href="<%= product_path(product) %>">
    <p>
    <img class="img-fluid img-thumbnail" src="<%= product.image %>"/>
    </p>
  </a>
  <div class="d-flex justify-content-between">
    <div class="product-brand mb-1"><%= product.brand %></div>
    <div class="product-id mb-1">#<%= product.id %></div>
  </div>

  <h5 class="product-name"><a href="<%= product_path(product) %>"><%= product.name %></a></h5>
  <h5 class="product-price"><%= number_to_currency(product.price, unit: 'đ', seperator: ',', format: "%n %u") %></h5>
</div>

rails-girl-demo-master/rails-girl-demo-master/app/views/products/index.html.erb
<div class="products container">
  <div class="row">
    <% @products.each do |product| %>
      <%= render 'product', product: product %>
    <% end %>
  </div>
</div>

rails-girl-demo-master/rails-girl-demo-master/app/views/products/show.html.erb
<div class="product-detail container d-flex justify-content-around">
  <img class="flex-grow-1 img-fluid img-thumbnail" src="<%= @product.image %>"/>
  <div class="product-detail-info ml-3">
    <div class="d-flex justify-content-between">
      <div class="product-brand mb-1"><%= @product.brand %></div>
      <div class="product-id mb-1">#<%= @product.id %></div>
    </div>

    <h4 class="product-name"><a href="<%= product_path(@product) %>"><%= @product.name %></a></h5>
    <p class="product-description"><%= simple_format(@product.description) %></p>
    <h5 class="product-price"><%= number_to_currency(@product.price, unit: 'đ', seperator: ',', format: "%n %u") %></h5>
  </div>
</div>